# Generated by Django 3.0.7 on 2020-06-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChestXrayImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('offset', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('finding', models.CharField(max_length=10000)),
                ('survival', models.BooleanField()),
                ('intubated', models.BooleanField()),
                ('went_icu', models.BooleanField()),
                ('needed_supplemental_o2', models.BooleanField()),
                ('extubated', models.BooleanField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_o2_saturation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wbc_count', models.DecimalField(decimal_places=2, max_digits=6)),
                ('netrophil_count', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lymphoctye_count', models.DecimalField(decimal_places=2, max_digits=6)),
                ('xray_view', models.CharField(choices=[('PA', 'Posteroanterior'), ('AP', 'Anteroposterior'), ('APS', 'Anteroposterior Supine'), ('L', 'Lateral'), ('AX', 'Axial'), ('CO', 'Coronal')], max_length=3)),
                ('modality', models.CharField(max_length=100)),
                ('image_date', models.DateField()),
                ('location', models.CharField(max_length=1000)),
                ('image_file', models.URLField(max_length=500)),
                ('study_doi', models.CharField(max_length=1000)),
                ('study_url', models.URLField(max_length=500)),
                ('image_license', models.CharField(max_length=1000)),
                ('clinical_notes', models.CharField(max_length=10000)),
                ('other_notes', models.CharField(max_length=10000)),
            ],
        ),
    ]
