# Generated by Django 3.0.7 on 2020-06-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chestxrayimage',
            old_name='image_file',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='chestxrayimage',
            old_name='lymphoctye_count',
            new_name='lymphocyte_count',
        ),
        migrations.RenameField(
            model_name='chestxrayimage',
            old_name='netrophil_count',
            new_name='neutrophil_count',
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='image_license',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='study_doi',
            field=models.CharField(max_length=200),
        ),
    ]
