# Generated by Django 3.0.7 on 2020-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0002_auto_20200610_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestxrayimage',
            name='image_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='lymphocyte_count',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='neutrophil_count',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='percent_o2_saturation',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='wbc_count',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
