# Generated by Django 3.0.7 on 2020-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0003_auto_20200610_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestxrayimage',
            name='xray_view',
            field=models.CharField(choices=[('PA', 'Posteroanterior'), ('AP', 'Anteroposterior'), ('L', 'Lateral'), ('AP Supine', 'Anteroposterior Supine'), ('Axial', 'Axial'), ('Coronal', 'Coronal')], max_length=10),
        ),
    ]
