# Generated by Django 3.0.7 on 2020-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0004_auto_20200610_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestxrayimage',
            name='in_icu',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='chestxrayimage',
            name='intubation_present',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='extubated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='finding',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='intubated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='needed_supplemental_o2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='offset',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='survival',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='went_icu',
            field=models.BooleanField(null=True),
        ),
    ]
