# Generated by Django 3.0.7 on 2020-06-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0005_auto_20200610_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestxrayimage',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('', 'Unknown')], max_length=1),
        ),
    ]
