# Generated by Django 3.0.7 on 2020-06-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0006_auto_20200610_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestxrayimage',
            name='lymphocyte_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='neutrophil_count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='percent_o2_saturation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='chestxrayimage',
            name='wbc_count',
            field=models.FloatField(null=True),
        ),
    ]
