# Generated by Django 3.0.7 on 2020-06-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chex', '0007_auto_20200610_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestxrayimage',
            name='patient_id',
            field=models.CharField(max_length=10),
        ),
    ]
